services:
  db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: nutrichat
      POSTGRES_PASSWORD: nutrichat_dev_pw_7h2k9
      POSTGRES_DB: nutrichat
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
